# Website settings
url: "https://barrier-options-hedging.mikush.in/"

# Jekyll build settings
repository: dmikushin/barrier-options-hedging

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
