# Website settings
url: "https://pyodide-jekyll.mikush.in/"

# Jekyll build settings
repository: dmikushin/pyodide-jekyll

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
